### ISSUE TITLE
How to prepare the BAM input?

### ISSUE THREAD

**Issue by homopolymer** [YosefLab/TRAPeS#1]
Hi, I notice that TRAPeS requires both mapped reads and unmapped reads in the BAM format as input. Could I have your advises on choosing the mapping software and human transcriptome reference to prepare the input data meeting the requirements of TRAPeS?

**Comment by shakea02** [comment]
Hi, 
We recommend using tophat2 as the alignment software, but any other software that align the reads to the genome can be used. For human data TRAPeS works on the latest genome assembly - hg38. 

Let me know if you have any other questions.
Best,
Shaked.

**Comment by homopolymer** [comment]
Hi, I used tophat2 to map Illumina reads to the reference sequence hg38.TCR.fa in the Data directory. But when I ran TRAPeS on the tophat2 output, there wasn't any result being yielded. I did check that there were 8328 reads mapped to the reference with high mapping quality in the tophat2 bam file. 

Here is the command that I used:

python $trapes -bam $PWD/tophat_out/accepted_hits.bam -unmapped $PWD/tophat_out/unmapped.bam -output $PWD/result -genome hg38 -singleCell

**Comment by shakea02** [comment]
Hi,
The input for TRAPeS should be tophat2 alignment to the hg38 genome, not to the hg38.TCR.fa file. You should align the reads to the standard hg38 genome, and TRAPeS will later extract the reads mapping to the TCR segments based on their genomic location.

Let me know if you have any other questions.
Best,
Shaked.
