### ISSUE TITLE
RSEM error

### ISSUE THREAD

**Issue by livnatje** [YosefLab/TRAPeS#3]
Hi Shaked,

Thanks for providing the code!

I'm trying to run it and get the following error. It seems to be working until the stage of writing the results to the summary file. Any idea why?

Thanks a lot,
Livnat

2016-11-30 12:19:30.017238 Finding productive CDR3
2016-11-30 12:19:35.054438 Writing results to summary file
Traceback (most recent call last):
  File "trapes.py", line 1667, in <module>
    args.singleCell, args.path, args.sumF, args.lowQ)
  File "trapes.py", line 54, in runTCRpipe
    minOverlap, rsem, bowtie2, lowQ)
  File "trapes.py", line 257, in runSingleCell
    unDictAlpha, unDictBeta, idNameDict)
  File "trapes.py", line 426, in makeSingleCellOutputFile
    writeChain(outF, 'alpha',alphaDict,alphaRsem, alphaBam, fastaDict,unDictAlpha, output, idNameDict)
  File "trapes.py", line 448, in writeChain
    rank = getRank(tcr, rsemDict, unRsemDict, isProd, noRsem)
UnboundLocalError: local variable 'rsemDict' referenced before assignment

**Comment by shakea02** [comment]
Hi Livnat,

Thank you for bringing this to my attention. I fixed the code and it should be working if you pull the new version.
The problem was caused because alpha chains were reconstructed but RSEM didn't run to quantify their expression. If TRAPeS still crashes (or if RSEM doesn't run even though it was supposed to) can you please also send me the following information:
1. The RSEM version you are using
2. The full log of your run
3. The command line you used to run TRAPeS.

Thanks,
Shaked

**Comment by livnatje** [comment]
Thank you Shaked!

Now it's working! I'm using rsem-1.2.8. I can also use rsem-1.2.4 if that's more compatible with TRAPeS.
  
Just to make sure I'm attaching here the TCR summary file that I got for one of the cells. Any reason why I don't get the number of reads?

Are you going to make the code run for single cells too (the -singleCell flag) any time soon? Could be very useful to run this on the servers/in parallel.

Thanks again!

[TCR..summary.xlsx](https://github.com/YosefLab/TRAPeS/files/625693/TCR.summary.xlsx)

**Comment by shakea02** [comment]
Hi Livnat,

After TCR reconstruction, we run RSEM to align the reads to the newly reconstructed transcripts and report the number of reads based on this alignment. If you can't see the number of reads this means that RSEM doesn't run correctly. There can be two main reasons for that:
1. RSEM doesn't sort the bam files which causes TRAPeS to crash. This can happen in some of the newer RSEM version. I have changed TRAPeS to sort the bam files in case RSEM doesn't sort them. Note that now you also need to include the path to samtools as a parameter (or leave empty if it's in the PATH variable).
2. RSEM doesn't run at all. If that's the case in the new version you should get an error message.  

If you still can't get the number of reads, can you send me the command line you used to run TRAPeS?

I agree that incorporating the singleCell flag will be useful. We will also allow to run TRAPeS in parallel when running it on a library of cells. This will be incorporated in the new TRAPeS version, but I don't have an estimate yet to when it will be ready (hopefully not too long!).

Best,
Shaked.

**Comment by livnatje** [comment]
Hi Shaked,

I ran the new version. It is running, but still doesn't give the number of reads.

python trapes.py -path /ahg/regevdata/projects/perturb_TILs_melanoma/TRAPeS-master/tmp3  \
	-output TRAPeS/TCR \
	-bam TOPHAT/accepted_hits.bam \
	-unmapped TOPHAT/unmapped.bam \
	-rsem /seq/regev_genome_portal/SOFTWARE/RSEM/rsem-1.2.8/ \
	-bowtie2 /seq/regev_genome_portal/SOFTWARE/bowtie2/bowtie2-2.1.0 \
	-genome hg38 -sumF TRAPeS_sum

I also get this warning 

Warning: The index file is older than the data file: /ahg/regevdata/projects/perturb_TILs_melanoma/TRAPeS-master/tmp3/cy98_CD45pos_CD8pos_S44/TOPHAT/accepted_hits.bam.bai

Thank you so much!

**Comment by shakea02** [comment]
Hi Livnat,
My apologies, I thought you were using RSEM version 1.2.28 and not 1.2.8. The 1.2.8 RSEM version does not support bowtie2 (only bowtie) and that is why RSEM didn't run on your samples. We will incorporate support for older RSEM versions and bowtie in the future. In the meantime I suggest switching to a newer RSEM version. 

As for the other warning - it just means that the index of the bam file was created before the actual bam file. This warning is generated when you replaced the bam file without indexing it again, but it can also happen if you copied the files from one folder to another and the index file got copied before the bam file and in that case you can ignore this warning.

Hope that was helpful, let me know if you have any other questions.
Best,
Shaked.
